/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.telas;

import com.mycompany.entities.FormaDePagamento;
import com.mycompany.entities.Pedido;
import com.mycompany.listaprodutos.Carrinho;
import com.mycompany.sistemavendas.Produto;
import java.awt.BorderLayout;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author ots
 */
public class TelaPagamento extends javax.swing.JPanel {

    private final Carrinho carrinho;
    /**
     * Creates new form TelaPagamentoJPanel
     */
    public TelaPagamento() {
        carrinho = Carrinho.getInstance();
        initComponents();
        initListaCarrinho();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcFormaPagamento = new javax.swing.JComboBox<>();
        jpCredito = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jsParcelas = new javax.swing.JSpinner();
        jlAviso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistCarrinho = new javax.swing.JList<>();
        jbConcluir = new javax.swing.JButton();

        jLabel2.setText("Total:");

        jLabel3.setText("R$");

        jlTotal.setText("jLabel4");

        jLabel4.setText("Forma de Pagamento:");

        jcFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crédito", "Débito" }));
        jcFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcFormaPagamentoActionPerformed(evt);
            }
        });

        jpCredito.setBorder(javax.swing.BorderFactory.createTitledBorder("Crédito"));

        jLabel5.setText("Quantidade de Parcelas:");

        jsParcelas.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout jpCreditoLayout = new javax.swing.GroupLayout(jpCredito);
        jpCredito.setLayout(jpCreditoLayout);
        jpCreditoLayout.setHorizontalGroup(
            jpCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCreditoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpCreditoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jsParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpCreditoLayout.setVerticalGroup(
            jpCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCreditoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jsParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pagamento");

        jlistCarrinho.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jlistCarrinho);

        jbConcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbConcluir.setText("Concluir");
        jbConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jpCredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(14, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcFormaPagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jbConcluir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jlTotal))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jpCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jbConcluir)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcFormaPagamentoActionPerformed
        JComboBox comboBox = (JComboBox) evt.getSource();
        if (comboBox.getItemCount() <= 0) return;
        
        int formaDePagamento = comboBox.getSelectedIndex();
        if(formaDePagamento == 0){
            this.jpCredito.setVisible(true);
            this.jsParcelas.setSize(30, this.jsParcelas.getSize().height);
            return;
        }
        
        this.jpCredito.setVisible(false);
    }//GEN-LAST:event_jcFormaPagamentoActionPerformed

    private void jbConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConcluirActionPerformed
       
        Pedido pedido = new Pedido(carrinho.getProdutos());
        int formaDePagamentoIndex = this.jcFormaPagamento.getSelectedIndex();
        if (formaDePagamentoIndex == 0){
            pedido.setFormaDePagamento(FormaDePagamento.CARTAO_CREDITO);
            int qtdParcelas = (int) jsParcelas.getValue();
            if (qtdParcelas <=0){
                JOptionPane.showMessageDialog(null, "A quantidade deve ser maior que zero", "Quantidade inadequada", JOptionPane.ERROR_MESSAGE);
                return;
            }
            pedido.setNumeroParcelas(qtdParcelas);
        }
        else pedido.setFormaDePagamento(FormaDePagamento.CARTAO_DEBITO);
        
        pedido.setValorTotal(carrinho.getTotal());
        
        Janela.telaRecibo = new TelaRecibo(pedido);
        JFrame janela = (JFrame) SwingUtilities.getWindowAncestor(this);
        janela.getContentPane().remove(Janela.telaPagamento);
        janela.add(Janela.telaRecibo, BorderLayout.CENTER);
        janela.pack();
    }//GEN-LAST:event_jbConcluirActionPerformed

    private void completarCompraComCredito(){
        
    }
    
    private void completarCompraComDebito(){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbConcluir;
    private javax.swing.JComboBox<String> jcFormaPagamento;
    private javax.swing.JLabel jlAviso;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JList<String> jlistCarrinho;
    private javax.swing.JPanel jpCredito;
    private javax.swing.JSpinner jsParcelas;
    // End of variables declaration//GEN-END:variables

    private void initListaCarrinho() {
        DefaultListModel listCarrinhoModel = new DefaultListModel<>();
        for (Produto produto : this.carrinho.getProdutos()) {
            listCarrinhoModel.addElement(produto.toString());
        }
        
        this.jlistCarrinho.setModel(listCarrinhoModel);
        String totalCarrinho = String.valueOf(carrinho.getTotal());
        this.jlTotal.setText(totalCarrinho);
    }
}
